train:
    ### GPU / WORKERS / SEED #####
    seed : 1023
    multi_gpu : True
    gpu : 1
    num_workers : 2

    ### DATASET ###
    transcripts_path_train : 'dataset/Train.txt'
    transcripts_path_valid : 'dataset/Valid.txt'
    noise_path : 'data_folder/Noise'
    vocab_label : 'dataset/labels.csv'

    ### STATUS ###
    checkpoint_every : 500  #train 중간마다 저장
    print_every : 5        #iteration 출력 업데이트 주기
    exp_day : 'audio'

    ### TRAIN ###
    num_epochs : 1
    batch_size : 4
    learning_rate : 0.0001

    
audio:
    feature_extract_by : 'None'
    transform_method : raw
    sample_rate : 14400
    n_mels : 80
    frame_length : 20 
    frame_shift : 10
    normalize : True
    spec_augment : True
    spec_augment_method : 2 ## 1 - default, 2 - background noise
    freq_mask_para : 12
    time_mask_num : 2
    freq_mask_num : 2
    n_channels : 1

model : 
    ## My Model config ##
    name : conf_a
    feature: logmelspectrogram
    use_npy: False
    split_balance : 0.1
    max_len  : 150

    # Train
    label_smoothing: 0.1
    alpha : 0.5

    # Metric
    use_att : True
    

encoder:
    # Encoder
    d_model : 512
    n_head : 8
    n_layers: 6
    dropout_p: 0.1
    encoder_bidirectional: True
    encoder_rnn_type: LSTM
    mask_conv: False


decoder:
    # Decoder
    d_model  : 512
    n_head   : 8
    ff_dim   : 512
    dropout_p: 0.3
    n_layers : 6
    vocab_size : 1159

    decoder_attn_mechanism: dot
    decoder_rnn_type: LSTM
    decoder_bidirectional: False
    decoder_use_beam: False