train:
    ### GPU / WORKERS / SEED #####
    seed : 1023
    multi_gpu : False
    num_workers : 4

    ### DATASET ###
    transcripts_path_train : 'dataset/Train.txt'
    transcripts_path_valid : 'dataset/Valid.txt'
    noise_path : 'data_folder/Noise'
    vocab_label : 'dataset/labels.csv'

    ### STATUS ###
    checkpoint_every : 500  #train 중간마다 저장
    print_every : 5        #iteration 출력 업데이트 주기
    exp_day : 'ctc_js2'

    ### TRAIN ###
    num_epochs : 100
    batch_size : 1
    scheduler : 'off'
    learning_rate : 0.00001


video:
    use_vid: False
    use_npz: False
    use_raw_vid: 'off'

    
audio:
    feature_extract_by : 'None'
    transform_method : raw
    sample_rate : 14400
    n_mels : 80
    frame_length : 20 
    frame_shift : 10
    normalize : True
    spec_augment : True
    spec_augment_method : 2 ## 1 - default, 2 - background noise
    freq_mask_para : 12
    time_mask_num : 2
    freq_mask_num : 2
    n_channels : 1


model : 
    ## My Model config ##
    name : conf_a
    feature: logmelspectrogram
    use_npy: False
    split_balance : 0.1
    
    ## Language Model
    use_jaso : True
    max_len  : 350

    # Train
    label_smoothing: 0.0
    alpha : 0.1 # attention rate
    

encoder:
    # Encoder
    d_model : 512
    n_head : 8
    n_layers: 6
    dropout_p: 0.1
    mask_conv: False
    fps: 60
    audio : 
        channel_0 : 64
        channel_1 : 128
        channel_2 : 256
        kernel_size : 79
        stride : 3
        # 80 : 5ms
        # 800 : 50ms

decoder:
    # Decoder
    d_model  : 512
    n_head   : 8
    ff_dim   : 512
    dropout_p: 0.3
    n_layers : 6

    method : ctc_only
    use_beam: False
    beam_width : 1