train:
    ### GPU / WORKERS / SEED #####
    seed : 1023
    multi_gpu : False
    num_workers : 3

    ### DATASET ###
    transcripts_path_train : 'dataset/Train.txt'
    transcripts_path_valid : 'dataset/Valid.txt'
    vocab_label : 'dataset/labels.csv'
    noise_path : 'data_folder/Noise'

    ### STATUS ###
    checkpoint_every : 500  #train 중간마다 저장
    print_every : 5        #iteration 출력 업데이트 주기
    exp_day : 'audT'

    ### TRAIN ###
    num_epochs : 200
    batch_size : 3
    learning_rate : 0.0001


video:
    use_vid: False
    
    
audio:
    feature_extract_by : 'None'
    transform_method : raw
    sample_rate : 14400
    n_mels : 80
    frame_length : 20
    frame_shift : 10
    normalize : True
    spec_augment : True
    spec_augment_method : 2 ## 1 - default, 2 - background noise
    freq_mask_para : 12
    time_mask_num : 2
    freq_mask_num : 2
    n_channels : 1

model : 
    ## My Model config ##
    name : conf_a
    feature: logmelspectrogram
    use_npy: False
    split_balance : 0.1
    max_len  : 350

    # Train
    label_smoothing: 0.1
    alpha : 0.5
    

encoder:
    # Encoder
    d_model : 512
    n_head : 8
    n_layers: 6
    dropout_p: 0.1
    mask_conv: False


decoder:
    # Decoder
    d_model  : 512
    n_head   : 8
    ff_dim   : 512
    dropout_p: 0.3
    n_layers : 6

    attn_mechanism: dot
    method : hybrid
    use_beam: False
    beam_width : 1
    ctc_att_rate : 0.5